#!/bin/bash
# Program:
#			Save the zshrc , bashrc gvim and so on
# History:
# 2018/12/01	Qiu Chao First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
NET_PATH=/media/cqiu/d/tool/stool/linux/scriptTool/netZTEOrWifi

sudo cp -rf ${NET_PATH}/environment.hk /etc/environment
sudo cp -rf ${NET_PATH}/sources.list.zte /etc/apt/sources.list
sudo cp -rf ${NET_PATH}/apt.conf.zte /etc/apt/apt.conf

echo "Finished setting hk server net" 
