#!/usr/bin/env perl
#################################################################################
#
# The confidential and proprietary information contained in this file may
# only be used by a person authorised under and to the extent permitted
# by a subsisting licensing agreement from Jeejio Limited.
#
#                 (C) COPYRIGHT 2018-2019 JEEJIO Limited.
#                       ALL RIGHTS RESERVED
#
# This entire notice must be reproduced on all copies of this file
# and copies of this file may only be made by a person if such person is
# permitted to do so under the terms of a subsisting license agreement
# from JEEJIO Limited.
#
#	       tar.gz format to bin format 
#	       ============
#
#
################################################################################

if ($#ARGV != 0) {
  print "\nUsage:  tar.gz format to bin format .log \n\n";
  die();
}
#-----delete the first input character when it including the "/" or "." and so on.
$_=$ARGV[0];
##s/\/\s*$//g; ## delete the "/" when the character including the "/"
s/\W+\s*$//g; ## delete the "/" when the character including the "/" or "." and so o
$inFileName = $_;
$outFileName=$inFileName."bin";
print "$inFileName \n"; 
print "$outFileName \n"; 

#----------------------------------------------------------
#Test the file exist or not. 
die "file $inFileName is not exist! \n" unless -e $inFileName;
#Open it.
open(IFILE,"<",$inFileName)  || die "open file $inFileName failed!\n" ;
binmode(IFILE);
open(OFILE,">",$outFileName) || die "open file $outFileName failed!\n";
binmode(OFILE);



################################################################################
# content begin
################################################################################
#
my $buffer = "";
while(read(IFILE,$buffer,1024)){
  syswrite(OFILE,$buffer,length($buffer));
  #print "$buffer";
  #print '=' x 24;
}
close(IFILE);
close(OFILE);

################################################################################
# content end 
################################################################################
print "tar.gz format to bin format successfully!\n";

close(IFILE);
close(OFILE);


